### ISSUE TITLE
Issues with the Instructions

### ISSUE THREAD

**Issue by yutosin** [psp2sdk/psp2sdk#61]
I've gone through the instructions for how to install psp2sdk and I felt like there were some holes as far as explanation (it's even missing a step 2). But also, I got through, filling in some of the blanks and when trying to build the hello world example I get this error: 

yutosin@ubuntu:~/psp2helloworld$ make
arm-none-eabi-gcc -Wall -specs=psp2.specs   -c -o main.o main.c
arm-none-eabi-gcc: error: psp2.specs: No such file or directory
make: *** [main.o] Error 1

I really wanna contribute and develop, but I can't get past this. Help?

**Comment by 173210** [comment]
See this.
https://github.com/psp2sdk/psp2sdk/wiki/A.-How-to-Install-PSP2SDK#3-download-psp2specsin
