### ISSUE TITLE
GCC unrecognized command line option during SDK compile

### ISSUE THREAD

**Issue by BrianBTB** [psp2sdk/psp2sdk#62]
configure:4489: checking stddef.h usability configure:4489: gcc -c -g -O2 -Wall -nostdlib -I$(top_srcdir)/include -mcpu=cortex-a9 -mfpu=neon-fp16 conftest.c >&5 gcc: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead gcc: error: unrecognized command line option '-mfpu=neon-fp16' configure:4489: $? = 1 configure: failed program was: | /* confdefs.h */

ubuntu 14.04 lts
https://launchpad.net/gcc-arm-embedded/+download
gcc-arm-none-eabi-4_9 extracted to /opt/toolchain

cd ~/psp2sdk
export PREFIX=/opt/toolchain
make

config.log is attatched
http://privatepaste.com/075d5c297d

**Comment by 173210** [comment]
```
export PATH=$PATH:/opt/toolchain/bin
```
