### ISSUE TITLE
stddef error

### ISSUE THREAD

**Issue by MisterAlex95** [psp2sdk/psp2sdk#63]
Hello,
I just installed the sdk following the wiki (with devkitPro) and I have a compilation error:

arm-none-eabi-gcc -Wall -specs=psp2.specs   -c -o main.o main.c
In file included from main.c:5:0:
a:\devkitpro\devkitarm\arm-none-eabi\include\stdio.h:35:20: fatal error: stddef.
h: No such file or directory
 #include <stddef.h>
                    ^
compilation terminated.
make: *** [main.o] Error 1

You can help me?

**Comment by MisterAlex95** [comment]
I tried adding stdder.h by hand. it's worse.

**Comment by 173210** [comment]
Your psp2.specs may be invalid. Anyway, this is not an issue of PSP2SDK.
