### ISSUE TITLE
memorymgr.h is missing

### ISSUE THREAD

**Issue by segadude** [psp2sdk/psp2sdk#65]
I installed the nightly of the ```psp2sdk``` on a Debain 8 based PC. I cloned ```psp2helloworld``` and ran ```make```. This is the result:
```
arm-none-eabi-gcc -Wall -specs=psp2.specs   -c -o draw.o draw.c
draw.c:10:35: fatal error: psp2/kernel/memorymgr.h: No such file or directory
 #include <psp2/kernel/memorymgr.h>
                                   ^
compilation terminated.
<builtin>: recipe for target 'draw.o' failed
make: *** [draw.o] Error 1
```
It seems that memorymgr.h is missing. I looked in ```/opt/devkitpro/devkitARM/psp2/include/psp2/kernel``` and memorymgr.h is not there. It seems that it is missing from the psp2-libs nightly zip I downloaded from wololo.net

**Comment by 173210** [comment]
`psp2/kernel/memorymgr.h` has been renamed to `psp2/kernel/sysmem.h`.
I updated psp2helloworld. Please check out.
https://github.com/173210/psp2helloworld/commit/b8db5b1ea873c8f4a81937d1cf722d946332b702
